server:
  port: 8086

spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://localhost:9411/

management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
        exposure:
            include: health
    endpoint:
        health:
            show-details: always


resilience4j:
  circuitbreaker:
    instances:
      employeeService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
#   retry:
#     instances:
#       serviceA:
#         registerHealthIndicator: true
#         maxRetryAttempts: 5
#         waitDuration: 10s
#   ratelimiter:
#     instances:
#       serviceA:
#         registerHealthIndicator: false
#         limitForPeriod: 10
#         limitRefreshPeriod: 10s
#         timeoutDuration: 3s

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka